trigger: none
pr: none

schedules:
- cron: '0 6 * * *'
  displayName: 'Daily 12AM CST'
  branches:
    include:
    - main
    - develop
  always: false

variables:
- group: dependency-track

resources:
  repositories:
  - repository: sharedTemplates
    type: git
    name: 'Projects/PipelineTemplates'
    ref: 'refs/heads/feature/vuln-test'

stages:

- stage: prep
  displayName: 'Prepare'

  jobs:

  # Execute gitversion
  - template: shared/versioning/gitversion.yml@sharedTemplates
    parameters:
      name: 'prep'

- stage: audit
  displayName: 'Audit'

  jobs:

  # Audit api vulnerabilities
  - template: dotnet/security/dtrack.yml@sharedTemplates
    parameters:
      name: 'audit_api'
      vmImage: 'ubuntu-22.04'
      pathToProject: './src/EtherGizmos.Shipyard.Api/EtherGizmos.Shipyard.Api.csproj'
      apiUrl: '$(DependencyTrack.ApiUrl)'
      apiKey: '$(DependencyTrack.ApiKey)'
      projectName: 'shipyard-api'
      projectType: 'APPLICATION'

  # Audit worker vulnerabilities
  - template: dotnet/security/dtrack.yml@sharedTemplates
    parameters:
      name: 'audit_worker'
      vmImage: 'ubuntu-22.04'
      pathToProject: './src/EtherGizmos.Shipyard.Worker/EtherGizmos.Shipyard.Worker.csproj'
      apiUrl: '$(DependencyTrack.ApiUrl)'
      apiKey: '$(DependencyTrack.ApiKey)'
      projectName: 'shipyard-worker'
      projectType: 'APPLICATION'

  # Audit web vulnerabilities
  - template: node/security/dtrack.yml@sharedTemplates
    parameters:
      name: 'audit_web'
      vmImage: 'ubuntu-22.04'
      nodeVersion: '22.x.x'
      pathToProject: './src/EtherGizmos.Shipyard.Web'
      apiUrl: '$(DependencyTrack.ApiUrl)'
      apiKey: '$(DependencyTrack.ApiKey)'
      projectName: 'shipyard-web'
      projectType: 'APPLICATION'
