trigger:
- main
- release/*
- develop

resources:
  repositories:
  - repository: sharedTemplates
    type: git
    name: 'Projects/PipelineTemplates'
    ref: 'refs/heads/feature/pre-post-tasks'

stages:

- stage: prep
  displayName: 'Prepare'

  jobs:

  # Execute gitversion
  - template: shared/versioning/gitversion.yml@sharedTemplates
    parameters:
      name: 'prep'

- stage: test
  displayName: 'Test'

  jobs:

  ## Perform dotnet unit tests
  #- template: dotnet/test/test.yml@sharedTemplates
  #  parameters:
  #    name: 'test_dotnet_unit'
  #    vmImage: 'ubuntu-22.04'
  #    testType: 'Unit'
  #    testPattern: '*UnitTests.csproj'
  #    codeCoverage: true
  #    artifactName: 'test-dotnet-unit'

  # Perform dotnet integration tests
  - template: dotnet/test/test.yml@sharedTemplates
    parameters:
      name: 'test_dotnet_integration'
      vmImage: 'ubuntu-22.04'
      testType: 'Integration'
      testPattern: '*IntegrationTests.csproj'
      codeCoverage: true
      artifactName: 'test-dotnet-integration'

  # Combine code coverage
  - template: shared/test/combine-coverage.yml@sharedTemplates
    parameters:
      name: 'coverage'
      artifacts:
      - 'test-dotnet-integration'
      dependsOn:
      - 'test_dotnet_integration'

- stage: publish
  displayName: 'Publish'

  jobs:

  # Publish dotnet api
  - template: dotnet/publish/application.yml@sharedTemplates
    parameters:
      name: 'publish_dotnet_api'
      vmImage: 'ubuntu-22.04'
      projectName: 'EtherGizmos.Shipyard.Api'
      artifactName: 'api'
      preTasks:

      # Install a specific node version
      - task: NodeTool@0
        displayName: 'Use Node.js 22.x.x'
        inputs:
          versionSpec: '22.x.x'

      # Restore npm packages
      - task: Npm@1
        displayName: 'Restore NPM Packages'
        inputs:
          command: 'ci'
          workingDir: './src/EtherGizmos.Shipyard.Api/wwwroot/_src'

  # Publish dotnet api (docker)
  - template: shared/container/dockerize-artifact.yml@sharedTemplates
    parameters:
      name: 'publish_dotnet_api_docker'
      dependsOn:
      - 'publish_dotnet_api'
      inputArtifactName: 'api'
      outputArtifactName: 'api-docker'
      dockerfilePath: 'containers/api.dockerfile'
      repository: 'etherfactor/shipyard-api'

  # Publish dotnet worker
  - template: dotnet/publish/application.yml@sharedTemplates
    parameters:
      name: 'publish_dotnet_worker'
      vmImage: 'ubuntu-22.04'
      projectName: 'EtherGizmos.Shipyard.Worker'
      artifactName: 'worker'

  # Publish dotnet worker (docker)
  - template: shared/container/dockerize-artifact.yml@sharedTemplates
    parameters:
      name: 'publish_dotnet_worker_docker'
      dependsOn:
      - 'publish_dotnet_worker'
      inputArtifactName: 'worker'
      outputArtifactName: 'worker-docker'
      dockerfilePath: 'containers/worker.dockerfile'
      repository: 'etherfactor/shipyard-worker'

  # Publish angular web ui
  - template: node/publish/application.yml@sharedTemplates
    parameters:
      name: 'publish_node_webui'
      vmImage: 'ubuntu-22.04'
      nodeVersion: '22.x.x'
      workingDir: './src/EtherGizmos.Shipyard.Web'
      buildCommand: 'build'
      distFolder: 'dist'
      projectName: 'EtherGizmos.Shipyard.Web'
      artifactName: 'web'

  # Publish angular web ui (docker)
  - template: shared/container/dockerize-artifact.yml@sharedTemplates
    parameters:
      name: 'publish_node_webui_docker'
      dependsOn:
      - 'publish_node_webui'
      inputArtifactName: 'web'
      outputArtifactName: 'web-docker'
      dockerfilePath: 'containers/web.dockerfile'
      extraFiles:
      - from: 'containers/apply-config-env.js'
        to: 'files'
      - from: 'containers/docker-entrypoint.web.sh'
        to: 'files'
      repository: 'etherfactor/shipyard-web'

- stage: verify
  displayName: 'Verify'

  jobs:

  # Verify default compose file works
  - template: shared/container/test-compose.yml@sharedTemplates
    parameters:
      name: 'test_container'
      composeFile: 'compose.yml'
      environmentExampleFile: '.env.example'
      environmentFile: '.env'
      images:
      - name: 'api'
        artifactName: 'api-docker'
        addTags:
        - 'latest'
      - name: 'worker'
        artifactName: 'worker-docker'
        addTags:
        - 'latest'
      - name: 'web'
        artifactName: 'web-docker'
        addTags:
        - 'latest'
      pullServices:
      - 'db'
      - 'rmq'
      - 'selenium'
      waitTimeout: 180
      verificationSteps:
      - bash: |
          curl --fail --silent --show-error http://localhost:7448/health
        displayName: 'Verify Shipyard API'
      - bash: |
          curl --fail --silent --show-error http://localhost:7447/assets/config.json > /dev/null
        displayName: 'Verify Shipyard Web'
      artifactName: 'compose-logs'
      env:
        SHIPYARD_WORKER_CLIENT_SECRET: 3HwNJcDqQmRomHNYAgFgCNMjH2Nq73a6
        SHIPYARD_WEB_LOG_APIKEY: tOMXIp94zMgMiGML2KJaeexUm04gh1sF
