<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Models", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Abstractions" Version="8.1.0" />
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(MSBuildProjectName).UnitTests" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.OAuth\EtherGizmos.Common.OAuth.csproj" />
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
  </ItemGroup>

</Project>
