<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Models", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Abstractions" Version="8.1.0" />
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="EtherGizmos.Common.Data.UnitOfWork" Version="0.1.0-alpha.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.9" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.OAuth\EtherGizmos.Common.OAuth.csproj" />
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
  </ItemGroup>

</Project>
