<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Models", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Abstractions" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="EtherGizmos.Common.Data.UnitOfWork" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.OAuth\EtherGizmos.Common.OAuth.csproj" />
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
  </ItemGroup>

</Project>
