<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Messaging", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.Messaging\EtherGizmos.Common.Messaging.csproj" />
  </ItemGroup>

</Project>
