<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Database", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EtherGizmos.Common.Composition.ChildContainers" />
    <PackageReference Include="EtherGizmos.Common.Data.Migrations" />
    <PackageReference Include="EtherGizmos.Common.Data.UnitOfWork" />
    <PackageReference Include="EtherGizmos.Common.Data.UnitOfWork.OpenTelemetry" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Shipyard.Models\EtherGizmos.Shipyard.Models.csproj" />
  </ItemGroup>

</Project>
