<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>637be093-1a3e-4938-979d-51c916cf9aae</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.2.4" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.2.4" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Shipyard.Worker\EtherGizmos.Shipyard.Worker.csproj" />
    <ProjectReference Include="..\EtherGizmos.Shipyard.Api\EtherGizmos.Shipyard.Api.csproj" />
  </ItemGroup>

</Project>
