<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.OData.ApiExplorer" Version="8.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.3.2" NoWarn="NU1608" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Shipyard.Models\EtherGizmos.Shipyard.Models.csproj" />
  </ItemGroup>

</Project>
