<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Notifications", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Events\Base\_layout.mjml.html" />
    <None Remove="Events\PackageDelivered\Templates\PackageDelivered.mjml.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Events\Base\Templates\_layout.mjml.html" />
    <EmbeddedResource Include="Events\PackageDelivered\Templates\PackageDelivered.mjml.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EtherGizmos.Common.Notifications.Email" />
    <PackageReference Include="EtherGizmos.Common.Notifications.Webhook" />
    <PackageReference Include="Mjml.Net" />
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
    <ProjectReference Include="..\EtherGizmos.Shipyard.Models\EtherGizmos.Shipyard.Models.csproj" />
  </ItemGroup>

</Project>
