<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Notifications", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
  </ItemGroup>

</Project>
