<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".OAuth", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EtherGizmos.Common.Cryptography.Certificates" Version="0.1.0-alpha.1" />
    <PackageReference Include="EtherGizmos.Common.Data.Migrations" Version="0.1.0-alpha.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.5.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.5.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.5.0" />
    <PackageReference Include="OpenIddict.Validation.ServerIntegration" Version="7.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EtherGizmos.Common.Utilities\EtherGizmos.Common.Utilities.csproj" />
  </ItemGroup>

</Project>
